// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFt-REz05vIYCwNbo-1WFYq9Ed3uhedIQ',
    appId: '1:522180221891:web:384d3988fa0495e2f9bb76',
    messagingSenderId: '522180221891',
    projectId: 'kochbox-8e889',
    authDomain: 'kochbox-8e889.firebaseapp.com',
    storageBucket: 'kochbox-8e889.firebasestorage.app',
    measurementId: 'G-JP7KNDCT98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpkEkvXxnYC-G7mb8fYIZ_m-bpIa1a0dY',
    appId: '1:522180221891:android:5f5b2dd19591773ef9bb76',
    messagingSenderId: '522180221891',
    projectId: 'kochbox-8e889',
    storageBucket: 'kochbox-8e889.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtAbJsrxpPh4Ogf21ZHRBSGedEu_ClJHE',
    appId: '1:522180221891:ios:cbd745f029446d7bf9bb76',
    messagingSenderId: '522180221891',
    projectId: 'kochbox-8e889',
    storageBucket: 'kochbox-8e889.firebasestorage.app',
    iosBundleId: 'com.example.kochApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtAbJsrxpPh4Ogf21ZHRBSGedEu_ClJHE',
    appId: '1:522180221891:ios:cbd745f029446d7bf9bb76',
    messagingSenderId: '522180221891',
    projectId: 'kochbox-8e889',
    storageBucket: 'kochbox-8e889.firebasestorage.app',
    iosBundleId: 'com.example.kochApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFt-REz05vIYCwNbo-1WFYq9Ed3uhedIQ',
    appId: '1:522180221891:web:71351fa49e662734f9bb76',
    messagingSenderId: '522180221891',
    projectId: 'kochbox-8e889',
    authDomain: 'kochbox-8e889.firebaseapp.com',
    storageBucket: 'kochbox-8e889.firebasestorage.app',
    measurementId: 'G-NDLQ5T9WS9',
  );
}
